
- name: variables to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning DevOps with AWS, Duration is 120Hrs, Trainer is Sivakumar Reddy"